version: "3.7"
services:
  web:
    image: node:14-alpine
    container_name: ms-frontend
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8080:8080"
    command: yarn serve